### ISSUE TITLE
Problems with figshare addon

### ISSUE THREAD

**Issue by JJ** [hubgit/figshare-api-explorer#1]
Hi, man, I know this is not the place, but I couldn't find the repo for the Mozilla Figshare addon to report the issue... The thing is since we have the new layout in GitHub I've lost the button. I can help patch it if I find the repo, so maybe that's all you've got to do. Thanks for your great work, anyway!

**Comment by hubgit** [comment]
Hi! I think you're looking for the [Code as a Research Object](https://github.com/mozillascience/code-research-object/issues) project :)

**Comment by hubgit** [comment]
Although actually the browser extension isn't in there, so thanks for the bug report - I'll take a look.
